"""init tabel

Revision ID: 85f5756f3951
Revises: 
Create Date: 2026-07-24 20:19:58.685721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f5756f3951'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_scan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('volume_avg_20d', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('price_change_pct', sa.Float(), nullable=True),
    sa.Column('high_30d', sa.Float(), nullable=True),
    sa.Column('low_30d', sa.Float(), nullable=True),
    sa.Column('signal_status', sa.String(length=20), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=False),
    sa.Column('triggers_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('search_date', sa.DateTime(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('has_foreign_interest', sa.Boolean(), nullable=False),
    sa.Column('news_items', sa.JSON(), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saham_fundamental',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('der', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('cf_positive', sa.Boolean(), nullable=True),
    sa.Column('cf_neg_quarters', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('catatan', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saham_fundamental')
    op.drop_table('news_cache')
    op.drop_table('daily_scan')
    # ### end Alembic commands ###
