"""delete source url

Revision ID: 8cb465f0f5a6
Revises: 9b7d34f7a2c1
Create Date: 2026-07-25 13:44:22.125422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '8cb465f0f5a6'
down_revision: Union[str, Sequence[str], None] = '9b7d34f7a2c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = inspect(op.get_bind())
    columns = {column["name"] for column in inspector.get_columns("saham_fundamental")}
    if "source_url" in columns:
        op.drop_column('saham_fundamental', 'source_url')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saham_fundamental', sa.Column('source_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
